### ISSUE TITLE
API for autoregistration

### ISSUE THREAD

**Issue by jakubvano** [Swinject/SwinjectAutoregistration#1]
Ideal API would be 
```
Container.register(service:initiliazer:)
```
however, as pointed out in [this comment](https://github.com/Swinject/Swinject/issues/132#issuecomment-242022958) it would colide with current usage of `Container.register(service:factory:)` method.

Options are
1. come up with a way to work around colision
2. rename method for autoregistration
3. swap arguments in autoregistration to `Container.register(initiliazer:service:)`

**Comment by yoichitgy** [comment]
@tkohout, would you investigate No. 1 above, first?

If there is no good workaround, we can take No. 2 or 3 above. IMO, No. 2 looks better because I think swapping argument order for method overload looks an inconsistent way generally.

**Comment by tkohout** [comment]
It could be solved by forbidding the  `Container.register(service:initiliazer:)` to use the trailing closure syntax. But I don't think that is possible.

Other possible solution is to somehow wrap the closure to another object and solving the conflict.
So the syntax would became:

`register(Service.self, initializer: Initializer(Service.init))`

But I am not a big fan of this approach as it requires more writing and creates new object just for sake of nicer name of register function.

**Comment by tkohout** [comment]
Btw, investigating further, it looks like swift can differentiate between the two closure `register(service:initiliazer:)` and `register(service:factory:)` if the resolver parameter is either explicitly typed like this:

```
container.register(Service1.self){ (r:ResolverType) in
   Service1(a: DependencyA())
}
```

or `r` is just used in the closure and the type is infered, therefore there is no conflict:

```
container.register(Service1.self){ r in
   Service1(a: r~>)
}
```

Even though it looks more digestible than before, adding the extension could break existing code, requiring to add ResolverType to closures where it is not used.

As a last a last thing, we could also use yet another operator (:D) for wrapping the initializer in another object, it could look something like this: https://gist.github.com/tkohout/45624b500932ae4770d12f59dfec5e18

You would than be able to call:

```
container.register(Service1.self, initializer: >>Service1.init)
```

without having and conflict. Don't mind the operator, I used `>>` but I actually have no idea how the operator for autoregistration should look like :D.

I would like to hear some feedback on this. 

Cheers 
Tomas

**Comment by tkohout** [comment]
So, after giving it a lot of thought I've decided to namespace the functionality so not to have any conflicts with the swinject registration function. The registration then looks like this:

```
container.auto.register(DependencyA.self, initializer: DependencyA.init)
```

I think it's the best from the bad options we have. I added this to the code and I think this issue can be closed.

**Comment by jakubvano** [comment]
Last week I started using `SwinjectAutoregistration` in the new project, and also came to the conclusion that renaming the function is the best option.
However, at the first glance `container.auto.register()` feels a bit weird - wouldn't `container.autoregister()` be simpler?

**Comment by tkohout** [comment]
I agree that `container.autoregister()` is simpler. My reasoning was that it than should be camel-cased like this `container.autoRegister()` being swift3 and all. And that doesn't look very nice when written next the regular `container.register` function. But I don't have very strong opinion on this. So as I see it there are two options:

1) `container.auto.register()`
2) `container.autoregister()`

@yoichitgy : Can you break it for us? This issue really takes too long and I would like to release the library asap.

**Comment by yoichitgy** [comment]
Sure, renaming the function to `autoregister()` is nice👍

**Comment by tkohout** [comment]
Done
