### ISSUE TITLE
Error installing using Carthage

### ISSUE THREAD

**Issue by igorkulman** [Swinject/SwinjectAutoregistration#13]
Trying to install `SwinjectAutoregistration` by adding

````
github "Swinject/Swinject" "2.0.0"
github "Swinject/SwinjectAutoregistration" "2.0.0"
````

to the `Cartfile`. Then calling `carthage update --platform iOS` fails with

````
*** Checking out SwinjectAutoregistration at "2.0.0"iff
Failed to write to /Users/igorkulman/Projects/Teamwire/iOS/Teamwire/Carthage/Checkouts/SwinjectAutoregistration/Carthage/Checkouts/Swinject: Error Domain=NSCocoaErrorDomain Code=516 "The file “Swinject” couldn’t be saved in the folder “Checkouts” because a file with the same name already exists." UserInfo={NSFilePath=/Users/igorkulman/Projects/Teamwire/iOS/Teamwire/Carthage/Checkouts/SwinjectAutoregistration/Carthage/Checkouts/Swinject, NSUnderlyingError=0x7fb79f10c1d0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
````

**Comment by yoichitgy** [comment]
The error says "because a file with the same name already exists."

Would you delete "Checkouts" folder and try running the command again? Or running `carthage update --use-submodules` might resolve the issue.

**Comment by igorkulman** [comment]
Still the same error even after removing the whole Carthage folder and using `--use-submodules`.

**Comment by yoichitgy** [comment]
I tried the following Cartfile, and couldn't reproduce the issue.

```
github "Swinject/Swinject" "2.0.0"
github "Swinject/SwinjectAutoregistration" "2.0.0"
```

Maybe running `carthage` command with `--verbose` option might get more hint to solve the problem.

**Comment by igorkulman** [comment]
Same error in an empty directory with the same Cartfile. The verbose switch did not provide any more info. But I am using the current Carthage 0.20.0 so I guess this is the problem.

**Comment by igorkulman** [comment]
Ok, it is definitely a Carthage bug: https://github.com/Carthage/Carthage/issues/1794. Sorry for bothering you.

**Comment by yoichitgy** [comment]
Thanks @igorkulman for finding and sharing the issue on Carthage😃
