### ISSUE TITLE
ERROR ITMS-90056: This bundle is invalid

### ISSUE THREAD

**Issue by threat70** [Swinject/SwinjectAutoregistration#19]
Hi, Today I try to release my app with SwinjectAutoregistration in dependency (via Carthage) and I receive error like 'ERROR ITMS-90056: This bundle is invalid. The Info.plist file is missing the required key: CFBundleVersion'
In project I found that in CFBundleVersion used parameter $(CURRENT_PROJECT_VERSION). But 'Current Project Version' is not installed in the build settings

Fix please or explain how I should use this.
Thanks.

**Comment by yoichitgy** [comment]
Thanks @threat70 for submitting the issue. We might need fix like SDWebImage did, though we still need some investigation in our case.

- https://github.com/rs/SDWebImage/issues/1780
- https://github.com/rs/SDWebImage/pull/1784/files

**Comment by threat70** [comment]
For submit the application I did the same in Carthage's checkouts folder

**Comment by threat70** [comment]
@yoichitgy Their fix is redundant, the setup of 'CURRENT_PROJECT_VERSION' is sufficient
```
diff --git a/SwinjectAutoregistration.xcodeproj/project.pbxproj b/SwinjectAutoregistration.xcodeproj/project.pbxproj
index 4a25656..0bedd36 100644
--- a/SwinjectAutoregistration.xcodeproj/project.pbxproj
+++ b/SwinjectAutoregistration.xcodeproj/project.pbxproj
@@ -1317,6 +1317,7 @@
                        isa = XCBuildConfiguration;
                        baseConfigurationReference = CD5B9E301D832A4F007ED05F /* iOS-Framework.xcconfig */;
                        buildSettings = {
+                               CURRENT_PROJECT_VERSION = 1;
                                INFOPLIST_FILE = "$(SRCROOT)/Sources/Info.plist";
                                PRODUCT_BUNDLE_IDENTIFIER = "com.swinject.SwinjectAutoregistration-iOS";
                        };
@@ -1326,6 +1327,7 @@
                        isa = XCBuildConfiguration;
                        baseConfigurationReference = CD5B9E301D832A4F007ED05F /* iOS-Framework.xcconfig */;
                        buildSettings = {
+                               CURRENT_PROJECT_VERSION = 1;
                                INFOPLIST_FILE = "$(SRCROOT)/Sources/Info.plist";
                                PRODUCT_BUNDLE_IDENTIFIER = "com.swinject.SwinjectAutoregistration-iOS";
                        };
```

**Comment by yoichitgy** [comment]
Thanks @threat70👍 I made a pull request.
