### ISSUE TITLE
Mistaking too many initialiser arguments for a tuple

### ISSUE THREAD

**Issue by jakubvano** [Swinject/SwinjectAutoregistration#2]
Issue described [here](https://github.com/Swinject/Swinject/issues/132#issuecomment-242704456):

There doesn't appear to be a compile-time solution to this, alternative would be to identify this case at run-time and fail with descriptive error message. 

Suggested ways of identifying the tuples:
1. [Type size measuring](https://github.com/Swinject/Swinject/issues/132#issuecomment-242921062)
2. [Type name checking](https://github.com/Swinject/Swinject/issues/132#issuecomment-243804527)

**Comment by yoichitgy** [comment]
As @tkohout noticed, No. 1 is not safe. I think taking No. 2 is better. A type name can be taken by `String(describing: type(of: ("foo", 1)))` in Swift3, and `String(("foo", 1).dynamicType)` in Swift 2.

**Comment by tkohout** [comment]
I agree that the option 2 is the better option. @jakubvano Will you take care of the implementation? Some function e.g.: `checkIsSingleArgument` that would be called from the autogenerated code

**Comment by yoichitgy** [comment]
Thanks @jakubvano for assigning yourself😃
