### ISSUE TITLE
Xcode 9b3 support

### ISSUE THREAD

**Issue by nahive** [Swinject/SwinjectAutoregistration#29]
Currently using autoregister in Xcode9b3 generates error `Ambiguous use of 'autoregister(_:name:initializer:)'` for code 
```swift
container.autoregister(ServiceType.self, initializer: Service.init)
```
where
```swift
protocol ServiceType {}

final class Service: ServiceType {
  private let dependecy: DependecyType

  init(dependency: DependencyType) {
    self.dependecy = dependecy
  }
}
```

From what I've gathered currently Xcode can't distinguish different autoregister functions, so adding only this function to the project works
```swift
func autoregister<Service, A>(_ service: Service.Type, name: String? = nil, initializer: @escaping (A) -> Service) -> ServiceEntry<Service>
```
but adding another like
```swift
func autoregister<Service, A, B>(_ service: Service.Type, name: String? = nil, initializer: @escaping (A, B) -> Service) -> ServiceEntry<Service>
```
generates error.

**Comment by tkohout** [comment]
Thanks for reaching out, I have just installed the 9b3 and see the same result. Although it's rather strange. 

The autoregistration works for inits with one argument but not with zero or more than one.
However, if there is a dynamic argument it works just fine:
e.g.:
```
container.autoregister(Service10.self, argument: DependencyB.self, initializer: Service10.init)
```

I will test some more tomorrow.

**Comment by nahive** [comment]
It may be that it's just this beta issue.

**Comment by tkohout** [comment]
Hello again,
as you say this might be just a quirk of this swift version as it is still in development. But it seems like there some changes in a way compiler handles closures:

For this example:
```
func autoregister<A, Service>(initializer: (A)->Service){ ... }
func autoregister<A, B, Service>(initializer: (A, B)->Service){ ... }

class Service2 {
    init(a: String, b: Int){}
}

autoregister(initiliazer: Service2.init)
```

Swift 3.2 first tries autoregister functions with multiple parameters. Only if there are no matches it use function with single parameter and passes the original parameters as a tuple.

Swift 4 however can't decide whether it is tuple of two arguments or a single argument and show ambiguous error.

There is a way to disambiguate the functions, just add extra parentheses like this:

```
func autoregister<A, B, Service>(initializer: ((A, B))->Service){ ... }
```
I am not sure whether this change is part of some proposal or it is just some compiler optimization. I found only [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md) considering tuples but as far as I know it should not be included in Swift 4.

You're free to use the fixed swift4 version of the library in [swift 4 branch](https://github.com/Swinject/SwinjectAutoregistration/tree/swift4). I will merge it when I'm sure the change will stick.

**Comment by nahive** [comment]
Awesome deduction, thank you. Will use your fixes branch for now.
