### ISSUE TITLE
Swift 4 Release

### ISSUE THREAD

**Issue by paulz** [Swinject/SwinjectAutoregistration#31]
Please release new version of the cocoapod with Swift 4 support.

This will allow us to remove branch specification from our `Podfile`:
```
pod 'SwinjectAutoregistration', 
:git => 'git@github.com:Swinject/SwinjectAutoregistration.git', 
:branch => 'swift4' 
```

Thank you for wonderful pod!

**Comment by tkohout** [comment]
Release [2.1.1](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.1.1)
