### ISSUE TITLE
Remove submodules

### ISSUE THREAD

**Issue by mpdifran** [Swinject/SwinjectAutoregistration#33]
We should remove submodules, similar to what we did for SwinjectStoryboard here: https://github.com/Swinject/SwinjectStoryboard/pull/44

Submodules prevent Carthage from sharing Swinject when using multiple Swinject dependencies, and can lead to build errors when including Carthage dependency projects as sub-projects.

**Comment by tkohout** [comment]
Thanks a lot, merged in https://github.com/Swinject/SwinjectAutoregistration/pull/41
