### ISSUE TITLE
Operator raise error for implicitly unwrapped optional type.

### ISSUE THREAD

**Issue by ecoopnet** [Swinject/SwinjectAutoregistration#38]
Hi, I cought some problem on the operator `~>` without right hand expression.

When I have `container.register(Service0.self) { r in Service0() }`,

it's ok:
```
let service: Service0 = container~>
```

But it raises error if the type is implicitly unwrapped optional:
```
let service: Service0! = container~>
```

I think implicitly unwrapped optional type is evil in almost all case.
But I have to use  implicitly unwrapped optional for injecting to view controllers with SwinjectStoryboard like below, so I hope to support implicitly unwrapped optional appropriately.

```
class MyViewController: UIViewController {
    var viewModel: MyViewModel!

    override func viewDidLoad() {
        super.viewDidLoad()
        // Use viewModel here
    }
}
```

```
extension SwinjectStoryboard {
    @objc class func setup() {
        defaultContainer.autoregister(MyViewModel.self, initializer: MyViewModel.init)

        defaultContainer.storyboardInitCompleted(MyViewController.self) { r, c in
              c.viewModel = r ~>  // crash!!
        }
}
```

environment:
- Xcode 9.4

**Comment by jakubvano** [comment]
What version of Swinject / SwinjectAutoregistration are you using?

**Comment by tkohout** [comment]
This should be resolved since the Type-Forwarding was added in Swinject 2.3.
