### ISSUE TITLE
watchOS deployment target.

### ISSUE THREAD

**Issue by raptorxcz** [Swinject/SwinjectAutoregistration#39]
iOS deployment target is iOS 8. This is totally fine. But watchOS deployment target is watchOS 4.3. Can we change it to something older let's say watchOS 3?

**Comment by jakubvano** [comment]
I don't expect there to be any technical issues with an older OS version, current limitation is most likely just a default value during project setup. Can you make a PR?

**Comment by raptorxcz** [comment]
PR created #40.

**Comment by jakubvano** [comment]
Resolved by #40
