### ISSUE TITLE
Xcode 10.2 Support

### ISSUE THREAD

**Issue by fnuky** [Swinject/SwinjectAutoregistration#47]
When I'm trying to rebuild framework for new Xcode 10.2, it allways fails.

Is it possible to support new Xcode 10.2? 

Many thanks!

**Comment by darrarski** [comment]
I have created PR #49 that solves the problem. Waiting to be reviewed and merged.

**Comment by tkohout** [comment]
Thanks. Support added in the [Release 2.6.0](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.6.0)
