### ISSUE TITLE
Auto-register on resolve

### ISSUE THREAD

**Issue by Evertt** [Swinject/SwinjectAutoregistration#58]
To be completely honest I haven't used this library yet. I was just reading the documentation and then I saw this line of code:

```swift
container.autoregister(MyService.self, initializer: MyService.init)
```

And then I  thought, well in that particular case why would you need to register the service at all? I come from a PHP background and in the Laravel framework the container has this feature that you can ask it to resolve a concrete class that you haven't even registered in it, because it can just auto-resolve all the bindings on the fly.

Wouldn't that be possible here too?

**Comment by tkohout** [comment]
the registration has to happen somewhere. This is limitation of Swinject rather than SwinjectAutoregistration.

And I don't think you can do this in Swift anyway - how would Swinject know which init to use?
