### ISSUE TITLE
Testing asserts

### ISSUE THREAD

**Issue by tkohout** [Swinject/SwinjectAutoregistration#6]
I would like to also test that the extension throws proper `assertionFailure` if the dependency is not resolved. But these asserts crashes the test suite which is obviously not desirable.

There is a pull request in Nimble that should be solving it but it appears to be dead for some time:
https://github.com/Quick/Nimble/pull/248 

There is apparently a way how to test preconditions described here: http://www.cocoawithlove.com/blog/2016/02/02/partial-functions-part-two-catching-precondition-failures.html which you can find either brilliant or ridiculously complicated .

We could use this though, but I am not sure if we want to mess the testing codebase with this code just to test the asserts. What do you think?

**Comment by yoichitgy** [comment]
It looks good to me to add code if we need for `assertionFailure` test.

You are intending to use the code from Cocoa with Love, not Nimble, right? The code in Cocoa with Love is brilliant though it is hacky as the author says. If the code is separated into  a single file, it's good to use it. (If we use it, we should follow [Cocoa with Love software license](http://www.cocoawithlove.com/about/).)

Another possibility is contributing to the Nimble's PR, but it looks stopped for a bug of Swift, so never mind this😉

What do you think, @jakubvano?

**Comment by jakubvano** [comment]
I fear that integrating this method might cause issues of some sort in future, given there are problems with integration to Nimble. However, I agree that we need a way to properly test features like `checkResolved` / tuple checking, and if there is no other way, this would be preferable to leaving untested code.

I struggled with testability of Swinject API before ([Swinject #99](https://github.com/Swinject/Swinject/issues/99)) and suggested that `resolve` methods could `throw` insead of return optional. This would enable testing of features we need, but also complicate API and require a lot of work.

**Comment by yoichitgy** [comment]
Thanks @jakubvano for your insight💡

@tkohout, I was thinking we are going to add the code only to the test target, correct? I understand @jakubvano worrying about the conflict with Nimble. If we have problems with Nimble in the future, we will remove or comment out the hacky code and test code for `assertionFailure`.

Another topic about the debuggability as @jakubvano mentioned, logging by `NSLog` or `print` before returning nil from `resolve` may be helpful enough for Swinject users, IMO.

**Comment by tkohout** [comment]
Looks like https://github.com/Quick/Nimble/pull/248 has been merged. Hopefully we can test it with the next release.
