### ISSUE TITLE
Swinject crash on iOS 14

### ISSUE THREAD

**Issue by Jovins** [Swinject/SwinjectAutoregistration#61]
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000102de8360
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [664]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   found                            	0x0000000102de8360 0x102be4000 + 2114400
1   found                            	0x0000000102de82e0 0x102be4000 + 2114272
2   found                            	0x000000010323059c 0x102be4000 + 6604188
3   found                            	0x00000001032308a8 0x102be4000 + 6604968
4   Swinject                      	0x00000001088ce40c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Resolver) -> (@out A) + 74764 (<compiler-generated>:0)
5   Swinject                      	0x00000001088ce468 partial apply for closure #1 in Container.resolve<A>(_:name:) + 74856 (<compiler-generated>:0)
6   Swinject                      	0x00000001088ce374 partial apply for thunk for @escaping @callee_guaranteed (@unowned @callee_guaranteed (@in_guaranteed B) -> (@out Any)) -> (@out Any) + 74612 (<compiler-generated>:0)
7   Swinject                      	0x00000001088ce39c partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed (@in_guaranteed B) -> (@out Any)) -> (@out Any) + 74652 (<compiler-generated>:0)
8   Swinject                      	0x00000001088c9204 Container.resolve<A, B>(entry:invoker:) + 53764 (Container.swift:309)
9   Swinject                      	0x00000001088c8ab8 Container._resolve<A, B>(name:option:invoker:) + 51896 (Container.swift:190)
10  Swinject                      	0x00000001088ca0dc Container.resolve<A>(_:) + 57564 (Container.swift:271)
11  Swinject                      	0x00000001088ca70c protocol witness for Resolver.resolve<A>(_:) in conformance Container + 59148 (<compiler-generated>:0)
12  found                            	0x0000000103230b0c 0x102be4000 + 6605580
13  Swinject                      	0x00000001088ce40c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Resolver) -> (@out A) + 74764 (<compiler-generated>:0)
14  Swinject                      	0x00000001088ce468 partial apply for closure #1 in Container.resolve<A>(_:name:) + 74856 (<compiler-generated>:0)
15  Swinject                      	0x00000001088ce374 partial apply for thunk for @escaping @callee_guaranteed (@unowned @callee_guaranteed (@in_guaranteed B) -> (@out Any)) -> (@out Any) + 74612 (<compiler-generated>:0)
16  Swinject                      	0x00000001088ce39c partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed (@in_guaranteed B) -> (@out Any)) -> (@out Any) + 74652 (<compiler-generated>:0)
17  Swinject                      	0x00000001088c9204 Container.resolve<A, B>(entry:invoker:) + 53764 (Container.swift:309)
18  Swinject                      	0x00000001088c8ab8 Container._resolve<A, B>(name:option:invoker:) + 51896 (Container.swift:190)
19  Swinject                      	0x00000001088ca0dc Container.resolve<A>(_:) + 57564 (Container.swift:271)
20  灵感                            	0x000000010323007c 0x102be4000 + 6602876
21  libdispatch.dylib             	0x0000000191a61ac8 0x191a5e000 + 15048
22  libdispatch.dylib             	0x0000000191a63250 0x191a5e000 + 21072
23  libswiftCore.dylib            	0x0000000195ce74d0 0x195951000 + 3761360

**Comment by tkohout** [comment]
See this issue: https://github.com/Swinject/SwinjectAutoregistration/issues/60 - it might be the same problem.

Otherwise paste the output of your console and your registration code.

**Comment by Jovins** [comment]
@tkohout How to solve this  crash problem?

**Comment by tkohout** [comment]
@Jovins You have to give me more information, as I said earlier

**Comment by tkohout** [comment]
@Jovins I am closing this as duplicate. Feel free to reopen if you think it is a different problem. 
I have also added section in documentation about this:
https://github.com/Swinject/SwinjectAutoregistration#swift-53
