### ISSUE TITLE
Allow dynamic in Package.swift

### ISSUE THREAD

**Issue by henriquegouveia** [Swinject/SwinjectAutoregistration#71]
Would it be possible to create a new version which contains the changes made in the Package.swift file?
I wanna use it as a dynamic library

**Comment by norbdev** [comment]
+1

**Comment by tkohout** [comment]
Sorry for the delay - [2.8.1](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.8.1) is out now.
