### ISSUE TITLE
Support for Xcode13 

### ISSUE THREAD

**Issue by spandanabatchu** [Swinject/SwinjectAutoregistration#75]

**Comment by norbdev** [comment]
+1

**Comment by mpdifran** [comment]
I'll add a ticket to look into this, this is definitely something we want to get out soon!

**Comment by Panajev** [comment]
Would we be able to use the 2.8.0 release of Swinject: https://github.com/Swinject/Swinject/releases/tag/2.8.0 ?

**Comment by mpdifran** [comment]
I'm not sure, we haven't tested that yet.

**Comment by tkohout** [comment]
[Version 2.8.1 ](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.8.1) Should be now working with Xcode 13.
