### ISSUE TITLE
Wrong version of Swinject on podspec

### ISSUE THREAD

**Issue by quangpc-zz** [Swinject/SwinjectAutoregistration#81]
Please fix podspec. Currently it's pointing to Swinject 2.7.1 instead of 2.8.1

**Comment by abouroubi** [comment]
Hope it will be merged soon !

**Comment by glauberl-ciandt** [comment]
> Hey, I still have this issue. If I put the latest versions into my Podfile:
> 
> ```
> github "Swinject/Swinject" "2.8.1"
> github "Swinject/SwinjectAutoregistration" "2.8.1"
> ```
> 
> I get this error message:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "Swinject":
>   In Podfile:
>     Swinject (= 2.8.1)
> 
>     SwinjectAutoregistration (= 2.8.1) was resolved to 2.8.1, which depends on
>       Swinject (= 2.7.1)
> ```
> 
> Is it possible that something is still wrong? :D The only way for me to get this work is to use `github "Swinject/SwinjectAutoregistration" "2.7.0"`

@norbert05 use `master` branch to perform your tests. Although the fix had been merged it is yet to be released.

**Comment by bradfol** [comment]
+1

**Comment by tkohout** [comment]
I have finally found some time to do the release, sorry for the long wait.

If someone would like to help with maintaining the repo I would be happy to invite them to the project.
