### ISSUE TITLE
Build fails on Carthage without xcframeworks

### ISSUE THREAD

**Issue by battlmonstr** [Swinject/SwinjectAutoregistration#83]
Version 2.7 works, but 2.8.1 fails with:
> error: There is no XCFramework found at '.../Carthage/Checkouts/SwinjectAutoregistration/Carthage/Build/Swinject.xcframework'. (in target 'SwinjectAutoregistration-iOS' from project 'SwinjectAutoregistration')

    carthage build --platform iOS --cache-builds SwinjectAutoregistration
    
carthage 0.38
xcode 13.1

**Comment by bradfol** [comment]
Were you able to find a solution for this?
