### ISSUE TITLE
the path does not point to a valid framework

### ISSUE THREAD

**Issue by RichBGru** [Swinject/SwinjectAutoregistration#84]
Creating xcframework file from repo https://github.com/Swinject/SwinjectAutoregistration project failed with error: the path does not point to a valid framework: ....../SwinjectAutoregistration/build/devices.xcarchive/Products/Library/Frameworks/Swinject.framework

Products directory is empty

**Comment by bradfol** [comment]
Are you using the SPM package to create the xcframework? Something else?

**Comment by bradfol** [comment]
Please reopen if this is still an issue, thank you.
