### ISSUE TITLE
Swift PM support?

### ISSUE THREAD

**Issue by JiLiZART** [Swinject/SwinjectAutoregistration#9]
Any plans to support swift package manager?

**Comment by yoichitgy** [comment]
Hi @JiLiZART. Thank you for your request. It's nice to have the Swift PM support😃👍👍 Are you interested in making a pull request?

**Comment by JiLiZART** [comment]
I can make it

**Comment by yoichitgy** [comment]
That's super great!!! Thanks @JiLiZART👍👍
